In [1]:
import torch

/home/student/my_env/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [11]:
a=torch.tensor([0,1,2,3])

In [3]:
torch.Tensor([0,1,2,3])

tensor([0., 1., 2., 3.])

In [7]:
torch.Tensor(2,3)

tensor([[8.7548e+35, 4.5570e-41, 9.2177e-36],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])

In [8]:
torch.arange(6).reshape(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [10]:
a0=torch.tensor([1.,2.,3.,4.])
a1=torch.tensor([5.,6.,7.,8.])
print(torch.dot(a0,a1))
print(torch.matmul(a0,a1))

tensor(70.)
tensor(70.)


In [16]:
print(a.dtype)
a.type()

torch.int64


'torch.LongTensor'

In [22]:
a0=torch.tensor([1,2,3],dtype=torch.float)
print(a0)
a1=a0.type(torch.LongTensor)
print(a1)

tensor([1., 2., 3.])
tensor([1, 2, 3])


In [24]:
a=torch.arange(6).reshape(2,3)
a.unsqueeze(0)

tensor([[[0, 1, 2],
         [3, 4, 5]]])

a1.py 自動微分

In [ ]:
def f(x):
    return (x[0]-2*x[1]-1)**2 + (x[1]*x[2]-1)**2 +1

def f_grad(x):
    z=f(x)
    z.backward()
    return x.grad

x=torch.tensor([1.,2.,3.], requires_grad=True)

for i in range(50):
    x= x-0.1*f_grad(x)
    x= x.detach().requires_grad_(True)
    print("x= ",x.data,", f= ",f(x).item())

関数＝エネルギー地形  
変数ｘ＝座標　と解釈すると  
x(requies_grad=True) は、その地点での勾配を自動計算し、情報はその地点に蓄える。x.gradでアクセス  
多分zはただの計算結果ではなくて、地点(=ただの数字)と地形の対応付けの情報が入ってる。backwardで固定して、変数に蓄える  
新たに情報を蓄えたいときは、上書きはなくてdetachしないといけない

とりあえず最初に書く

In [28]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np

iris2.py GPU　の使用

In [31]:
device = torch.device("cuda:0"
                      if torch.cuda.is_available()
                      else "cpu")

chapter2