In [24]:
import slackweb
slack = slackweb.Slack(url="https://hooks.slack.com/services/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")
slack.notify(text="slack test")

'ok'

In [15]:
import os
print(os.path.basename(__file__))

NameError: name '__file__' is not defined

In [21]:
if 0:
    print(1)

In [5]:
import datetime
print(str(datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=9)))))

2022-12-27 19:02:45.890402+09:00


In [13]:
import json
file_description={"rowAttr":"epoch","rowVal":"accuracy","batch_size":1}
file_description["datetime"]=str(datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=9))))
dum=json.dumps(file_description)
print(dum)
loa=json.loads(dum)
loa["batch_size"]+1

{"rowAttr": "epoch", "rowVal": "accuracy", "batch_size": 1, "datetime": "2022-12-27 20:38:53.730510+09:00"}


2

In [4]:
d={"x":1,"y":2}
ind_to_word = {ind: word for word, ind in d.items()}
ind_to_word[4]="z"
ind_to_word

{1: 'x', 2: 'y', 4: 'z'}

In [45]:
import torch
x = torch.rand(5, 3)
print(x)
print( torch.cuda.is_available() )
print(x.device)
x[:,0] 
print(x.repeat(2,1,1)[:,2])

tensor([[0.9940, 0.5410, 0.2480],
        [0.4557, 0.8743, 0.3006],
        [0.3977, 0.7274, 0.1699],
        [0.5278, 0.6885, 0.3823],
        [0.5366, 0.3785, 0.0592]])
True
cpu
tensor([[0.3977, 0.7274, 0.1699],
        [0.3977, 0.7274, 0.1699]])


In [62]:
b_s=2
in_tensor=torch.tensor(range(18),dtype=float).view(2,9)
weights=torch.tensor([0.1,0.5,0.9,1,2,3],dtype=float).view(2,3)
print(in_tensor,weights)
'''out_tensor = torch.nn.functional.conv1d(in_tensor.view(b_s, 1, -1),
                        weights.view( 1,b_s, -1),
                        groups=b_s)'''
out_tensor =[torch.nn.functional.conv1d(in_tensor[idx].view(1, 1, -1),weights[idx].view(1, 1, -1)) for idx in range(b_s)]
out_tensor=torch.stack(out_tensor).view(b_s,-1)
print(out_tensor)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12., 13., 14., 15., 16., 17.]], dtype=torch.float64) tensor([[0.1000, 0.5000, 0.9000],
        [1.0000, 2.0000, 3.0000]], dtype=torch.float64)
tensor([[ 2.3000,  3.8000,  5.3000,  6.8000,  8.3000,  9.8000, 11.3000],
        [62.0000, 68.0000, 74.0000, 80.0000, 86.0000, 92.0000, 98.0000]],
       dtype=torch.float64)


In [66]:
torch.stack([torch.tensor([1,2]),torch.tensor([3,4])])
torch.stack([torch.tensor([1,2])])

tensor([[1, 2]])

In [69]:
print(torch.zeros(2,3,1))
print(torch.zeros([2,3,1]))
torch.tensor([1,2])+torch.tensor([3,4])

tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]])
tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]])


tensor([4, 6])

In [37]:
batch_size=1
memory =torch.Tensor(range(batch_size*12)).view(batch_size,3,4)
print(memory)
#write_freq =torch.Tensor([2,1,1.5,1,1.2,1]).view(batch_size,3)
write_freq =torch.Tensor([1,1.2,1]).view(batch_size,3)
print(write_freq)
sorted_freq, fai_idx = torch.topk(write_freq, 2, dim=1, largest=False)
print(sorted_freq,fai_idx)
fai_rep=fai_idx.unsqueeze(2).repeat(1,1,4)
print(fai_rep)
print(torch.gather(memory,1,fai_rep)) #dim=1
print(memory)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]])
tensor([[1.0000, 1.2000, 1.0000]])
tensor([[1., 1.]]) tensor([[0, 2]])
tensor([[[0, 0, 0, 0],
         [2, 2, 2, 2]]])
tensor([[[ 0.,  1.,  2.,  3.],
         [ 8.,  9., 10., 11.]]])
tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]])


In [29]:
batch=2 #controller_s=3, mem_unit_s=4
h_state=torch.tensor([0,1,2]).repeat(batch,1)
read_data=torch.tensor(range(batch*4)).view(-1,4)
print(torch.cat([h_state] + read_data, dim=-1))

TypeError: can only concatenate list (not "Tensor") to list

In [2]:
x.permute(1,0)

tensor([[0.2234, 0.4054, 0.0190, 0.7539, 0.6234],
        [0.2093, 0.9621, 0.5451, 0.2532, 0.1844],
        [0.2107, 0.8999, 0.4119, 0.2263, 0.7994]])

In [21]:
x = torch.rand(5, 3)
y = torch.rand(5, 1)
print(x)
print(y)
print(torch.cat([x,y],dim=1))

tensor([[0.0274, 0.5690, 0.0338],
        [0.9364, 0.7745, 0.3300],
        [0.9591, 0.3667, 0.9758],
        [0.7249, 0.4088, 0.8803],
        [0.1636, 0.2850, 0.2497]])
tensor([[0.3696],
        [0.1669],
        [0.2264],
        [0.4007],
        [0.1937]])
tensor([[0.0274, 0.5690, 0.0338, 0.3696],
        [0.9364, 0.7745, 0.3300, 0.1669],
        [0.9591, 0.3667, 0.9758, 0.2264],
        [0.7249, 0.4088, 0.8803, 0.4007],
        [0.1636, 0.2850, 0.2497, 0.1937]])


In [3]:
import numpy as np

In [9]:
grave_dnc1_meanError =[9,39.2,39.6,0.4,1.5,6.9,9.8,5.5,7.7,9.6,3.3,5.0,3.1,11.0,27.2,53.6,32.4,4.2,64.6,0,16.7]
grave_dnc1_acc= (100-np.array(grave_dnc1_meanError))/100
taskid_str_list =[str(i) for i in range(1,21)]
taskid_str_list.append("mean")

In [12]:
for ind,task in enumerate(taskid_str_list):
    print(task+":"+str(grave_dnc1_acc[ind]))

1:0.91
2:0.608
3:0.604
4:0.996
5:0.985
6:0.9309999999999999
7:0.902
8:0.945
9:0.9229999999999999
10:0.904
11:0.9670000000000001
12:0.95
13:0.9690000000000001
14:0.89
15:0.728
16:0.46399999999999997
17:0.6759999999999999
18:0.958
19:0.35400000000000004
20:1.0
mean:0.833
