In [68]:
import sys
print(sys.path)
sys.path.append("/work/my_modified_ntm/bgavDNC_src")
print(sys.path)

['/work/my_modified_ntm', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/work/my_modified_ntm/bgavDNC_src']
['/work/my_modified_ntm', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages', '/work/my_modified_ntm/bgavDNC_src', '/work/my_modified_ntm/bgavDNC_src']


In [69]:
from task_implementations.bAbI.bAbI import *
from utils import project_path, init_wrapper
import os
import numpy as np

In [70]:
task = bAbITask(os.path.join("tasks_1-20_v1-2", "en-10k"))
print("Loaded task")

Loaded task


In [71]:
task = bAbITask(os.path.join("tasks_1-20_v1-2", "en-10k"))
print("Loaded task")

Loaded task


In [72]:
print(task.vector_size)
print(task.ind_to_word)

160
{0: '-', 1: '*', 2: 'mary', 3: 'is', 4: 'no', 5: 'longer', 6: 'in', 7: 'the', 8: 'bedroom', 9: '.', 10: 'daniel', 11: 'moved', 12: 'to', 13: 'hallway', 14: '?', 15: 'sandra', 16: 'bathroom', 17: 'not', 18: 'office', 19: 'went', 20: 'john', 21: 'kitchen', 22: 'travelled', 23: 'back', 24: 'garden', 25: 'yes', 26: 'journeyed', 27: 'sumit', 28: 'tired', 29: 'where', 30: 'will', 31: 'go', 32: 'why', 33: 'did', 34: 'grabbed', 35: 'pajamas', 36: 'there', 37: 'get', 38: 'yann', 39: 'bored', 40: 'jason', 41: 'thirsty', 42: 'got', 43: 'football', 44: 'antoine', 45: 'milk', 46: 'hungry', 47: 'took', 48: 'apple', 49: 'picked', 50: 'up', 51: 'bill', 52: 'gave', 53: 'fred', 54: 'what', 55: 'give', 56: 'handed', 57: 'jeff', 58: 'who', 59: 'received', 60: 'left', 61: 'passed', 62: 'put', 63: 'down', 64: 'dropped', 65: 'discarded', 66: 'carrying', 67: 'nothing', 68: 'how', 69: 'many', 70: 'objects', 71: 'one', 72: 'none', 73: 'two', 74: 'three', 75: 'cinema', 76: 'yesterday', 77: 'julie', 78: 'scho

In [73]:
print(task.x_shape)
print(task.mask)

[None, None, 160]
[None, None, 1]


In [74]:
print(task.x_train_stories.keys())

dict_keys(['/work/my_modified_ntm/bgavDNC_src/task_implementations/bAbI/tasks_1-20_v1-2/en-10k/qa9_simple-negation_train.txt', '/work/my_modified_ntm/bgavDNC_src/task_implementations/bAbI/tasks_1-20_v1-2/en-10k/qa20_agents-motivations_train.txt', '/work/my_modified_ntm/bgavDNC_src/task_implementations/bAbI/tasks_1-20_v1-2/en-10k/qa5_three-arg-relations_train.txt', '/work/my_modified_ntm/bgavDNC_src/task_implementations/bAbI/tasks_1-20_v1-2/en-10k/qa14_time-reasoning_train.txt', '/work/my_modified_ntm/bgavDNC_src/task_implementations/bAbI/tasks_1-20_v1-2/en-10k/qa10_indefinite-knowledge_train.txt', '/work/my_modified_ntm/bgavDNC_src/task_implementations/bAbI/tasks_1-20_v1-2/en-10k/qa11_basic-coreference_train.txt', '/work/my_modified_ntm/bgavDNC_src/task_implementations/bAbI/tasks_1-20_v1-2/en-10k/qa1_single-supporting-fact_train.txt', '/work/my_modified_ntm/bgavDNC_src/task_implementations/bAbI/tasks_1-20_v1-2/en-10k/qa3_three-supporting-facts_train.txt', '/work/my_modified_ntm/bgavDNC

In [75]:
xlis=task.y_test_stories["/work/my_modified_ntm/bgavDNC_src/task_implementations/bAbI/tasks_1-20_v1-2/en-10k/qa8_lists-sets_test.txt"]
print(type(xlis))
xarr=np.array(xlis)
print(xarr.shape)

<class 'list'>
(200,)


/tmp/ipykernel_46505/1198921949.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  xarr=np.array(xlis)


In [76]:
def idlist_to_word(lis):
    return [task.ind_to_word[elm] for elm in lis]
print(idlist_to_word( task.x_test_stories["/work/my_modified_ntm/bgavDNC_src/task_implementations/bAbI/tasks_1-20_v1-2/en-10k/qa8_lists-sets_test.txt"][0] ))
print(idlist_to_word( xlis[0]) )

['mary', 'got', 'the', 'milk', 'there', '.', 'john', 'moved', 'to', 'the', 'bedroom', '.', 'what', 'is', 'mary', 'carrying', '?', '-', 'john', 'picked', 'up', 'the', 'football', 'there', '.', 'john', 'journeyed', 'to', 'the', 'bathroom', '.', 'what', 'is', 'john', 'carrying', '?', '-', 'john', 'went', 'to', 'the', 'garden', '.', 'daniel', 'went', 'back', 'to', 'the', 'hallway', '.', 'what', 'is', 'john', 'carrying', '?', '-', 'john', 'went', 'back', 'to', 'the', 'bathroom', '.', 'mary', 'went', 'to', 'the', 'office', '.', 'sandra', 'went', 'back', 'to', 'the', 'kitchen', '.', 'mary', 'travelled', 'to', 'the', 'hallway', '.', 'john', 'travelled', 'to', 'the', 'bedroom', '.', 'john', 'picked', 'up', 'the', 'apple', 'there', '.', 'what', 'is', 'john', 'carrying', '?', '-', '-', 'sandra', 'travelled', 'to', 'the', 'bedroom', '.', 'sandra', 'journeyed', 'to', 'the', 'kitchen', '.', 'what', 'is', 'john', 'carrying', '?', '-', '-']
['mary', 'got', 'the', 'milk', 'there', '.', 'john', 'moved',

In [154]:
cost_value=999
batch_size=3
data_batch, seqlen, m = task.generate_data(cost=cost_value, batch_size=batch_size, train=True)
print(seqlen)
print(m.shape)
print(task.vector_size,data_batch[0].shape,data_batch[1].shape)



[98, 102, 113]
(3, 113, 1)
160 (3, 113, 160) (3, 113, 160)


20

In [166]:
#test
num_tasks = len(task.x_test_stories)
print(num_tasks)
for (inp,output) in zip(task.x_test_stories.items(), task.y_test_stories.items()):
    #inp, out　どちらも(key,value) のタプルっぽい。key=storyごとにforで回す　forのひとつひとつは1key= 1task_type
    print(type(inp))
    print(len(inp))
    print(inp[1][:2])
    break

20
<class 'tuple'>
2
[[20, 22, 12, 7, 13, 9, 2, 26, 12, 7, 16, 9, 29, 3, 20, 14, 0, 10, 19, 23, 12, 7, 16, 9, 20, 11, 12, 7, 8, 9, 29, 3, 2, 14, 0, 20, 19, 12, 7, 13, 9, 15, 26, 12, 7, 21, 9, 29, 3, 15, 14, 0, 15, 22, 12, 7, 13, 9, 20, 19, 12, 7, 24, 9, 29, 3, 15, 14, 0, 15, 19, 23, 12, 7, 16, 9, 15, 11, 12, 7, 21, 9, 29, 3, 15, 14, 0], [15, 22, 12, 7, 21, 9, 15, 22, 12, 7, 13, 9, 29, 3, 15, 14, 0, 2, 19, 12, 7, 16, 9, 15, 11, 12, 7, 24, 9, 29, 3, 15, 14, 0, 15, 22, 12, 7, 18, 9, 10, 26, 12, 7, 13, 9, 29, 3, 10, 14, 0, 10, 26, 12, 7, 18, 9, 20, 11, 12, 7, 13, 9, 29, 3, 15, 14, 0, 20, 22, 12, 7, 16, 9, 20, 26, 12, 7, 18, 9, 29, 3, 10, 14, 0]]


In [176]:
import torch
import torch.nn as nn
intlis=torch.tensor([[3,3,1,0]],dtype=float)
soft1=nn.functional.softmax(intlis,dim=1)
soft2=nn.functional.softmax(soft1,dim=1)
print(soft1)
print(soft2)
label=torch.tensor([1])
cros=nn.CrossEntropyLoss()
loss1=cros(intlis,label)
loss2=cros(soft1,label)
print(loss1,loss2)
print(soft1+1e-2)

tensor([[0.4576, 0.4576, 0.0619, 0.0228]], dtype=torch.float64)
tensor([[0.3012, 0.3012, 0.2027, 0.1950]], dtype=torch.float64)
tensor(0.7817, dtype=torch.float64) tensor(1.2001, dtype=torch.float64)
tensor([[0.4676, 0.4676, 0.0719, 0.0328]], dtype=torch.float64)


In [107]:

testints=torch.tensor([[1,2,1,0],
                        [1,4,0,1],
                        [0,0,10,0]],
                        dtype=float)
labels=torch.tensor([0,1,2]) # bad, good, great
cross_nored=nn.CrossEntropyLoss(reduction='none')
cros=nn.CrossEntropyLoss()
print(cross_nored(testints,labels))
print(cros(testints, labels))


tensor([1.6265e+00, 1.1144e-01, 1.3619e-04], dtype=torch.float64)
tensor(0.5794, dtype=torch.float64)


In [143]:
def mycross_OH_3Dto3D(input, target, reduction='mean'):
    if reduction!="mean": raise ValueError('reduction is not implemented yet')
    if (input.dim()!=3) or (target.dim()!=3): raise ValueError('invalid dim')
    ls_input=nn.functional.log_softmax(input, 2)
    nll=-1*torch.einsum( 'blf,blf->bl',ls_input,target) 
    #nll=torch.mean(nll,dim=1)
    return nll

In [140]:
testints3=torch.tensor([[[1,2,1,0],
                        [1,4,0,1],
                        [0,0,10,0]]],
                        dtype=float)
labels3=torch.tensor([[0,1,2]]) # bad, good, great
labels3_onehot=nn.functional.one_hot(labels3,num_classes=4).to(torch.float64)
print(testints3.dim(),labels3_onehot.dim())
print(testints3.dtype,labels3_onehot.dtype)
print(mycross_OH_3Dto3D(testints3,labels3_onehot))

3 3
torch.float64 torch.float64
tensor([[1.6265e+00, 1.1144e-01, 1.3619e-04]], dtype=torch.float64)


In [151]:
def my_masked_mean(loss,mask):
    masked = loss * mask[:, :, 0]
    mask_batchs =torch.sum(mask[:,:,0],dim=1)
    return torch.mean(torch.sum(masked,dim=1)/ mask_batchs)

In [173]:
#mask test!!!
noisedints=torch.tensor([[[1,2,1,0],
                        [1,4,0,1],
                        [0,0,10,0],
                        [10,0,0,0],[0,10,0,0],[0,0,10,0],[10,0,0,0]],
                        [[1,2,1,0],
                        [1,4,0,1],
                        [0,0,10,0],
                        [10,0,0,0],[0,10,0,0],[0,0,10,0],[10,0,0,0]]],
                        dtype=float)
noised_labels=torch.tensor([[0,1,2,3,3,3,3],[0,1,2,3,3,3,3]])
noised_onehot=nn.functional.one_hot(noised_labels)
mask=torch.tensor([[[1],[1],[1],[0],[0],[0],[0]],[[0],[1],[1],[0],[0],[0],[0]]])
print(noisedints.size(), noised_labels.size(), noised_onehot.size(),mask.size())

loss =mycross_OH_3Dto3D(noisedints,noised_onehot.to(torch.float64))
print(loss)

masked = loss * mask[:, :, 0]
print(masked) # == cros
print(torch.mean(masked))

print(my_masked_mean(loss,mask))
mask_batchs=torch.sum(mask[:,:,0],dim=1)
print(mask_batchs)
print(torch.sum(masked,dim=1))
print(torch.sum(masked,dim=1)/ mask_batchs)

torch.Size([2, 7, 4]) torch.Size([2, 7]) torch.Size([2, 7, 4]) torch.Size([2, 7, 1])
tensor([[1.6265e+00, 1.1144e-01, 1.3619e-04, 1.0000e+01, 1.0000e+01, 1.0000e+01,
         1.0000e+01],
        [1.6265e+00, 1.1144e-01, 1.3619e-04, 1.0000e+01, 1.0000e+01, 1.0000e+01,
         1.0000e+01]], dtype=torch.float64)
tensor([[1.6265e+00, 1.1144e-01, 1.3619e-04, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 1.1144e-01, 1.3619e-04, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00]], dtype=torch.float64)
tensor(0.1321, dtype=torch.float64)
tensor(0.3176, dtype=torch.float64)
tensor([3, 2])
tensor([1.7381, 0.1116], dtype=torch.float64)
tensor([0.5794, 0.0558], dtype=torch.float64)


tensor(0.3176, dtype=torch.float64)

In [150]:
loss.size()

torch.Size([1, 7])

In [85]:
print(nn.functional.one_hot(labels))

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])
