In [2]:
import numpy as np

In [7]:
#def generate_data(
batch_size=1
length=4
size=5
cuda=-1

input_data = np.zeros((batch_size, 2 * length + 1, size), dtype=np.float32)
target_output = np.zeros((batch_size, 2 * length + 1, size), dtype=np.float32)

input_data

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)

In [8]:
sequence = np.random.binomial(1, 0.5, (batch_size, length, size - 1))
sequence


array([[[0, 1, 0, 1],
        [0, 0, 0, 0],
        [0, 0, 1, 0],
        [1, 0, 1, 0]]])

In [9]:
input_data[:, :length, :size - 1] = sequence
input_data[:, length, -1] = 1  # the end symbol
target_output[:, length + 1:, :size - 1] = sequence

print(input_data)
print(target_output)



[[[0. 1. 0. 1. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [1. 0. 1. 0. 0.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 1. 0. 1. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [1. 0. 1. 0. 0.]]]
